apiVersion: release-notes/v2
kind: bug-fix
area: networking
releaseNotes:
- |
  **Fixed** an issue where `AuthorizationPolicy`'s WaypointAccepted status condition was not being updated to reflect the resolution of a `GatewayClass` target reference.
